#ifndef CLIENTSRC_C_MACROS_H
#define CLIENTSRC_C_MACROS_H

#define MODE_CMD 0
#define MODE_GUI 1

#define LOGIN_ERR -1
#define CREDENTIALS_VERIFIED 1

#define REGISTER_ERR 0
#define REGISTER_SUCCESS 1
#define REGISTER_DUPLICATE 2

#define CHECK_NO 0
#define CHECK_OK 1

#define NOT_PARAM 0
#define IS_PARAM 1

#define APP_STANDBY 0
#define APP_LAUNCHED 1

#define CHANGE_NO 0
#define CHANGE_OK 1

#define SALT "OJIH8UGYV7_çà26481502"

#endif //CLIENTSRC_C_MACROS_H
